import { IEmployee } from '../Interfaces/employee.interface'

export const employeesListData: IEmployee[] = [
    {
        firstName: 'kakashi',
        lastName: 'hatake',
        email: 'kakashi@gmail.com',
        password: 'kakashi@123',
        leaves: 5,
        availableLeaves: 3,
        admin: false,
        blockCount: 0,
        block: false,
        appliedLeaves: [],
        disapproveLeavesComments: [],
    },
    {
        firstName: 'obito',
        lastName: 'uchiha',
        email: 'uchiha.obito@gmail.com',
        password: 'obito@123',
        leaves: 7,
        availableLeaves: 5,
        admin: false,
        blockCount: 0,
        block: false,
        appliedLeaves: [],
        disapproveLeavesComments: [],
    },
    {
        firstName: 'pain',
        lastName: '',
        email: 'pain123@gmail.com',
        password: 'pain@123',
        leaves: 5,
        availableLeaves: 3,
        admin: false,
        blockCount: 0,
        block: false,
        appliedLeaves: [],
        disapproveLeavesComments: [],
    },
    {
        firstName: 'monkey D',
        lastName: 'luffy',
        email: 'luffy.d@gmail.com',
        password: 'luffy@123',
        leaves: 9,
        availableLeaves: 2,
        admin: false,
        blockCount: 0,
        block: false,
        appliedLeaves: [],
        disapproveLeavesComments: [],
    },
    {
        firstName: 'goku',
        lastName: '',
        email: 'goku@gmail.com',
        password: 'goku@123',
        leaves: 9,
        availableLeaves: 7,
        admin: false,
        blockCount: 0,
        block: false,
        appliedLeaves: [],
        disapproveLeavesComments: [],
    },
]

export const usersListData = [
    {
        firstName: 'itachi',
        lastName: 'uchiha',
        email: 'uchiha.itachi@gmail.com',
        password: 'itachi@123',
        leaves: 12,
        availableLeaves: 9,
        admin: true,
        blockCount: 0,
        block: false,
        appliedLeaves: [],
        disapproveLeavesComments: [],
    },
    {
        firstName: 'kakashi',
        lastName: 'hatake',
        email: 'kakashi@gmail.com',
        password: 'kakashi@123',
        leaves: 5,
        availableLeaves: 3,
        admin: false,
        blockCount: 0,
        block: false,
        appliedLeaves: [],
        disapproveLeavesComments: [],
    },
    {
        firstName: 'obito',
        lastName: 'uchiha',
        email: 'uchiha.obito@gmail.com',
        password: 'obito@123',
        leaves: 7,
        availableLeaves: 5,
        admin: false,
        blockCount: 0,
        block: false,
        appliedLeaves: [],
        disapproveLeavesComments: [],
    },
    {
        firstName: 'pain',
        lastName: '',
        email: 'pain123@gmail.com',
        password: 'pain@123',
        leaves: 5,
        availableLeaves: 3,
        admin: false,
        blockCount: 0,
        block: false,
        appliedLeaves: [],
        disapproveLeavesComments: [],
    },
    {
        firstName: 'monkey D',
        lastName: 'luffy',
        email: 'luffy.d@gmail.com',
        password: 'luffy@123',
        leaves: 9,
        availableLeaves: 2,
        admin: false,
        blockCount: 0,
        block: false,
        appliedLeaves: [],
        disapproveLeavesComments: [],
    },
    {
        firstName: 'goku',
        lastName: '',
        email: 'goku@gmail.com',
        password: 'goku@123',
        leaves: 9,
        availableLeaves: 7,
        admin: false,
        blockCount: 0,
        block: false,
        appliedLeaves: [],
        disapproveLeavesComments: [],
    },
]
